### ISSUE TITLE
flatpak packages out of date

### ISSUE THREAD

**Issue by adam-ce** [JetpackDuba/Gitnuro#111]
I've been looking for a nice linux gui client for quite long. so thank you for this. it looks great!

i have some issues with ssh push though. seems like you fixed that in v1.2, but you forgot to make the flatpak package (https://flathub.org/apps/com.jetpackduba.Gitnuro). would be cool if you can do that!

thanks again,
adam

**Comment by JetpackDuba** [comment]
Hey!

I didn't forget, I had to get some permissions from the Flathub admins and it took quite some time. The permissions were accepted a few days ago but I ended up delaying the release because I plan to release today v1.2.1, so I'll do everything together.

In other words, the relase will be available tomorrow if everything goes as expected.

For any other flatpak-specific issues please open an issue here https://github.com/flathub/com.jetpackduba.Gitnuro/

Thanks!

**Comment by JetpackDuba** [comment]
I've merged this new release, it will be available in Flathub in about 3h :smile:
