### ISSUE TITLE
Allow to continue externally started rebase

### ISSUE THREAD

**Issue by Mingun** [JetpackDuba/Gitnuro#143]
**Is your feature request related to a problem? Please describe.**
I see no reasons why Gitnuro could not continue externally started rebase

**Describe the solution you'd like**
Allow to work with repository as if rebase was initiated from Gitnuro

**Describe alternatives you've considered**
None

**Additional context**
In that case a rebase was started by the CLI, but merge conflict is appeared. I've run Gitnuro, but it is unable to show current state of the repository:
![Gitnuro_003](https://github.com/JetpackDuba/Gitnuro/assets/450131/3ee42d79-6e39-4a36-be52-8e823606f23c)

**Comment by JetpackDuba** [comment]
Hey! 

It's because unfortunately JGit doesn't provide a way to know the ongoing rebase state (It isn't easy unless you start parsing files in .git/rebase-merge and even then it doesn't show the live state of the rebase in the other Git implementation such as the official CLI), so it's not really worth to implement it myself, as it's weird to mix between clients when doing a rebase interactive.
