### ISSUE TITLE
Missing documentation for unsupported JDK 21 installed by IntelliJ IDEA

### ISSUE THREAD

**Issue by drick0230** [JetpackDuba/Gitnuro#144]
**Describe the bug**

If you follow the "DEVELOPMENT.md" instructions, Gradle is not able to build the project.

**Steps to fix the problem**

1. [Download and install "Java(TM) SE Development Kit 17"](https://www.oracle.com/java/technologies/downloads/#java17).
2. Go into "'File' -> 'Settings...' -> 'Build, Execution, Deployment' -> 'Build Tools' -> 'Gradle'".
3. Select the project ("Gitnuro") under "Gradle Projects".
4. Select "17 Oracle OpenJDK version 17.0.7" in the "Gradle JVM" dropdown field.

**Expected behaviour**

Having the steps to download, install and select the JDK in the documentation.

A [branch](https://github.com/drick0230/Gitnuro/tree/grable-build-error) has already been created on a fork to update the  "DEVELOPMENT.md" documentation.
A pull request should follow in the next days.

**Desktop**

- OS: Windows 11 and Debian LTS (tested in a VM)

**Comment by drick0230** [comment]
The label should probably be [documentation](https://github.com/JetpackDuba/Gitnuro/labels/documentation).

**Comment by JetpackDuba** [comment]
Not a fan at all of the steps. You should already be familiar with Kotlin and the JDK before diving into Gitnuro, otherwise you will get quite lost (even more in the Compose parts).

JDK 17 is not necessary either, I'm building using JDK 20 (I'll move it to 21 LTS as soon as it is released) for Gradle and Gitnuro itself. Even if using JDK  17, any version of it should work, it does not have to be specifically 17.0.7. An example would be the latest release, which is built using 17.0.3.

LibSSH official docs are quite self explanatory, there is no need to replicate their information, as there the risk of being out of date if no one notices if the original source changes.

The issue in the title seems better suited for Stackoverflow, or even here if you simply wanted to share your issue. Gradle tends to show weird errors with certain environments, having all them listed is kinda pointless.

**Comment by drick0230** [comment]
> Not a fan at all of the steps. You should already be familiar with Kotlin and the JDK before diving into Gitnuro, otherwise you will get quite lost (even more in the Compose parts).
> 
> JDK 17 is not necessary either, I'm building using JDK 20 (I'll move it to 21 LTS as soon as it is released) for Gradle and Gitnuro itself. Even if using JDK 17, any version of it should work, it does not have to be specifically 17.0.7. An example would be the latest release, which is built using 17.0.3.
> 
> LibSSH official docs are quite self explanatory, there is no need to replicate their information, as there the risk of being out of date if no one notices if the original source changes.
> 
> The issue in the title seems better suited for Stackoverflow, or even here if you simply wanted to share your issue. Gradle tends to show weird errors with certain environments, having all them listed is kinda pointless.

"IntelliJ IDEA Community Edition (2023.1.3)" install "JetBrains Runtime 21" when there is no JDK installed on the machine and there is no ".idea" folder containing the "Project Structure" settings (including the SDK used by the project).

I removed what I did previously and added a note  into "Setting up an IDE" about not supporting "JetBrains Runtime 21" yet.
The changes are in this [branch](https://github.com/drick0230/Gitnuro/tree/grable-build-error).

If you wish, we can also close the issue and do nothing.

**Comment by JetpackDuba** [comment]
Actually, that looks much better. Feel free to open a PR and thank you!
