### ISSUE TITLE
GeforceNow start record

### ISSUE THREAD

**Issue by dizyaa** [JetpackDuba/Gitnuro#20]
**Describe the bug**
GeforceNow recording app, when it started. 

**To Reproduce**
1. Install app
2. Start

**Expected behavior**
When app is starting, GN does not start recording

**Screenshots**
![image](https://user-images.githubusercontent.com/53047160/196009054-aa7c43fc-7b55-4293-b453-57ee20f576c7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Education Edition
 - Version 1.0.1

**Comment by ProjectInfinity** [comment]
What does the symbol on the bottom right indicate? The message you are being displayed is just letting you know to use Alt-Z to open the "in-game overlay", not that it is recording. This happens because your Geforce Experience application is incorrectly detecting Gitnuro as a game. You may have to add it to a sort of exclusion list in your Geforce Experience application. It is not something I think that needs to be resolved on Gitnuro's end.

**Comment by grizeldi** [comment]
From my experience Geforce Experience will detect anything that uses OpenGL/DirectX/Vulkan hardware acceleration as a game by default, so it's definitely a problem on the Geforce Experience side. Not sure how one would go about blacklisting programs from being detected as a game though.

**Comment by JetpackDuba** [comment]
As already well explained by @ProjectInfinity and @grizeldi , I can't help here, it's something related to Nvidia's software.

**Comment by dizyaa** [comment]
Thank you for your time. This is not a critical issue, but it only occurs when starting Gitnuro and Jetbrains Toolbox. Maybe there is some way to add to the black list. If I find references, i will immediately come back here)
