### ISSUE TITLE
Authentication failed

### ISSUE THREAD

**Issue by phifuh** [JetpackDuba/Gitnuro#220]
I tried pushing a commit to my github repo, but I only get the error "authentication not supported"

I am currently using github desktop where I can push it to the repo. 
I read in the issue #204 #205 that you have to install the gcm but even after installing i am not getting a "pop window" to login/create the acces token. I might need to config it by the CLI? 

Anyway, even tho this might not be a "bug" - "bug", I still think gitnuro should make the process of authentication easier and guide the user. Not everyone will use CLI or read in past issues on github

**Comment by JetpackDuba** [comment]
Hey! 

Can you post your gitconfig?

It's in the roadmap to add support for third party services at some point (as seen in #205) but not in the near future. However, improving the error could be something interesting and it was added to #30 . 

It wasn't working out of the box because it probably used some kind of GitHub-specific auth such as GH CLI. Gitnuro 1.4 fixes some issues with GH CLI auth but it's not out yet (planned this week tho, release notes are ready).

**Comment by JetpackDuba** [comment]
Sorry for the late response.

The helper has to point to the Git Credentials Manager full path as shown in the readme FAQ.

I know it's not the best way tho. I've been experimenting a bit to avoid all this extra config/overhead but it needs more testing.

Given that I'm waiting for the release of a dependency, I'll try to test it further to avoid all these issues with users migrating from github cli or other credentials helpers.

**Comment by JetpackDuba** [comment]
Don't use your password, you have to generate a token in GitHub that will be used for auth. I will have to add a warning as this issue arises often... 

https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens

**Comment by Ashutosh-pixel** [comment]
@JetpackDuba 

yes please add warning or something because every new user facing this issue.
