### ISSUE TITLE
Enable discussion on github and v1.4 release.

### ISSUE THREAD

**Issue by Escain** [JetpackDuba/Gitnuro#228]
Hi, 

I wonder if you could enable "Discussion" on this Github repo. For example, this request would fit better there than as an issue.

Originally, my question is about V1.4
I see that all features from 1.4 as done on the roadmap since long. I would like to try it if a release could be downloaded.

Or are you planning to wait until v1.5 and skip 1.4?

By the way: thank you for this great tool.

**Comment by JetpackDuba** [comment]
Discusions created :smile: 

I'm not planing to skip 1.4 but I'm awaiting for Compose 1.7. There is a big bug in 1.6 and another one in 1.7 alpha02 which has been fixed in Android but not yet multiplatform.

Copying and pasting my own commit:

> In compose 1.6.0 the pointer would be changed to the default after some rendering-heavy operation or combining crossfade animations with pointerHoverIcon  in the inner composables.
> 
> This version introduces another where click events are dismissed if the cursor has moved even slightly.
> 
> Related to:
> Youtrack issue: https://youtrack.jetbrains.com/issue/CMP-5069/1.7.0-alpha01-Moving-after-initiating-a-click-cancels-it
> 
> Compose Multiplatform PR: https://github.com/JetBrains/compose-multiplatform-core/pull/1445
> 
> Google gerrit patch: https://android-review.googlesource.com/c/platform/frameworks/support/+/3170403

I've been looking into how to do cross platform builds and have nightly builds for users who want to start testing newer changes but I'm not familiar with Github CI so I'm a bit slow. If everything goes well, probably before the end of this week I'll have a beta version of 1.4

**Comment by JetpackDuba** [comment]
The CI has been a bit of a pain but it seems to be working fine now. Beware of the 2 known issues that can be kinda annoying.

https://github.com/JetpackDuba/Gitnuro/releases/tag/1.4.0-beta01
