### ISSUE TITLE
[Feature] Reset confirmation dialog

### ISSUE THREAD

**Issue by RichardFevrier** [JetpackDuba/Gitnuro#25]
Not having a confirmation dialog to reset something could lead to loose work.
It would be a nice to have 🙂

**Comment by JetpackDuba** [comment]
Do you mean resetting a file or a commit?

**Comment by RichardFevrier** [comment]
File

**Comment by JetpackDuba** [comment]
The first iteration of Gitnuro had dialogs for such destructive actions but I've removed them for a good cause. Having a dialog poping up when you may just missclick 1% of the times is annoying and if I add the option of "Do not show again this dialog" the users will just mark it and we would have the same issue.

So, how can we solve this issue? By backing up discarded files. Once I release Gitnuro 1.1 (this weekend if possible), I'll share a roadmap for 1.2 and create issues here (instead of having them written in a notepad :sweat_smile: ).

I'll leave this issue open for now until I create one with the proper solution.

Thanks for your feedback :smiley:

**Comment by JetpackDuba** [comment]
I'm closing this in favor of https://github.com/JetpackDuba/Gitnuro/issues/39
