### ISSUE TITLE
Suggestion: Swap Push/Pull and Stash/Pop button positions

### ISSUE THREAD

**Issue by Renari** [JetpackDuba/Gitnuro#253]
After you make a commit usually the next action you would want to do is push. Similarly when interacting with stashes you're likely interacting more with the left panel. However the buttons on the top bar for these actions are both on the other side, I think it would make more sense if they were swapped.

**Comment by JetpackDuba** [comment]
Hello,

Thanks for sharing your suggestion but I do not agree. While stashes are at the left, branches and remotes are also there. The branches in the graph panel are also aligned at the left.

In any case, the order is decided by ordering the most to least used buttons as if it was LTR text, where you start looking at the row by the left and continue to the right. I even thought of swapping it for users whose OS was using a RTL language but ended up discarding the idea to prevent confusion as coding is done in "english".

If you want to quickly push after comitting, you can press `CTRL+P` (or `CTRL+U` for pulling). Beware that these keybinding are undocumented in Gitnuro 1.4.X because they are subject to change.
