### ISSUE TITLE
Submodules support

### ISSUE THREAD

**Issue by JetpackDuba** [JetpackDuba/Gitnuro#29]
Support for submodules ~~as well as hidding them from the uncommited changes list when necessary.~~

**Comment by Escain** [comment]
Hi, 

In case it can help, I would like to share how I imagine the sub-module support for a git client. The different points are in order of priority (again from my POV):

1) Sub-modules can be open as a repo: Even if most aspects of the sub-modules is missing, being able to open in Gitnuro a sub-module as a normal repo would unblock the usage of Gitnuro in those cases.
Note: It's currently difficult to get around this:
- Usually, the parent repo depends on the child repo (that's the goal), so not cloning the sub-module makes the project to not compile.
- Cloning the sub-module as a normal repo at the place where the sub-module should be is not ideal neither: the parent repo shows hundreds of changes due to that folder. Adding them to the .gitignore would also affect other users if pushed by error.
- Updates to that sub-module either arrive to early (changes are not compatible), or too late (bugs).

2) When pulling a repo, if a sub-module exist which is not at it relevant commit (not necessarily the HEAD), Gitnuro should ask if to 'git update' also the sub-module. Maybe a "No, Yes, No to All, Yes to All" dialog? One of the main sources of errors when working with sub-modules comes from having them outdated.

3) When cloning a repo, clone also sub-modules. Or ask if to clone sub-modules. (Very similar to previous case)

4) The diff for a specific sub-module should help knowing which of the two versions is (if any) prior to the other: It's easy with sub-modules to have it outdated, which means the diff of the sub-module only shows a SHA which can be tedious to understand (I would need to search for the SHA in the history to understand it). Having an indication of "prior->next" of the two states would help to determine if I am pushing a new version or reverting changes.

5) The sub-module should allow to switch to that sub-repo, and from the sub-repo, get back to the main repo: This allows basic navigation through the project.

I think it's not a good idea to hide the sub-module from the uncommitted changes, they are changes to be committed or reverted as any other change.

In the hope it can help
Best regards

**Comment by JetpackDuba** [comment]
Hey!

Thanks for this detailed feedback, it's greatly appreciated!

>     1. Sub-modules can be open as a repo: Even if most aspects of the sub-modules is missing, being able to open in Gitnuro a sub-module as a normal repo would unblock the usage of Gitnuro in those cases.

Agreed, I've already got it implemented but requires further testing.

> 
>     * Usually, the parent repo depends on the child repo (that's the goal), so not cloning the sub-module makes the project to not compile.
> 
>     * Cloning the sub-module as a normal repo at the place where the sub-module should be is not ideal neither: the parent repo shows hundreds of changes due to that folder. Adding them to the .gitignore would also affect other users if pushed by error.

Submodules will be cloned as expected, cloning them as normal repositories would be really weird.

>     * Updates to that sub-module either arrive to early (changes are not compatible), or too late (bugs).

I'm not sure what do you mean in this sentence.

> 
>     2. When pulling a repo, if a sub-module exist which is not at it relevant commit (not necessarily the HEAD), Gitnuro should ask if to 'git update' also the sub-module. Maybe a "No, Yes, No to All, Yes to All" dialog? One of the main sources of errors when working with sub-modules comes from having them outdated.



>     3. When cloning a repo, clone also sub-modules. Or ask if to clone sub-modules. (Very similar to previous case)

Yeah, it will be an optional check.

>     4. The diff for a specific sub-module should help knowing which of the two versions is (if any) prior to the other: It's easy with sub-modules to have it outdated, which means the diff of the sub-module only shows a SHA which can be tedious to understand (I would need to search for the SHA in the history to understand it). Having an indication of "prior->next" of the two states would help to determine if I am pushing a new version or reverting changes.

I'm not sure if there is any way to do that. I can't promise anything but I'll try.

>     5. The sub-module should allow to switch to that sub-repo, and from the sub-repo, get back to the main repo: This allows basic navigation through the project.

Double clicking on a repo (or using the contextual menu) will open the submodule in a new tab that can be used as a normal repository (or that's tha main idea)

> 
> I think it's not a good idea to hide the sub-module from the uncommitted changes, they are changes to be committed or reverted as any other change.

I agree, I'll edit my original message.
