### ISSUE TITLE
Project not building after cloning

### ISSUE THREAD

**Issue by nishp77** [JetpackDuba/Gitnuro#53]
**Describe the bug**
Cloned the project and try to build it

**To Reproduce**
1. Click build after cloning it in IDE

**Expected behavior**
Project to build successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/35785259/206886455-3c50b8c4-596e-48d7-ae1e-b1ec8b44fb24.png)

**Desktop (please complete the following information):**
 - OS: Linux 
 - Version Fedora 36

**Comment by JetpackDuba** [comment]
Seems something is wrong with the intellij setup. This can be useful https://stackoverflow.com/questions/70259098/could-not-initialize-class-sun-util-calendar-zoneinfofile-intellij

You could also try to create an empty project to see if it builds and compare what are the differences. Gitnuro itself should build without any issue as the latest commits are the ones used for the 1.1.1 releases, I haven't changed anything since then.

**Comment by nishp77** [comment]
Saw the post on stackoverflow earlier but still didn't work

**Comment by nishp77** [comment]
Yes IDE was flatpak removed it and it works now
