### ISSUE TITLE
Cannot find libskiko-linux-arm64.so.sha256, proper native dependency missing

### ISSUE THREAD

**Issue by endim8** [JetpackDuba/Gitnuro#85]
**Describe the bug**
Unable to run the app on M1 mac (Fedora via asahi linux).

full log:
https://pastebin.com/cwXupUUS

**Desktop (please complete the following information):**
 - OS: Fedora, installed via flathub
 - Version 1.1.1

**Comment by ProjectInfinity** [comment]
Are you able to build from source?

If you open up build.gradle.kts, change the following line
https://github.com/JetpackDuba/Gitnuro/blob/main/build.gradle.kts#L29
to
`implementation(compose.desktop.linux_arm64)` and try building.

Does this work for you?

I believe the issue is that the provided binary in the flatpak is compiled for x86_64. So until Gitnuro is offered with a ARM64 compatible binary you will need to build it yourself.

**Comment by endim8** [comment]
![image](https://user-images.githubusercontent.com/26939824/218071879-a8f842cf-5927-4e07-b17f-f9d299d154e5.png)

thank you! it works when building manually, didn't need to change the build.gradle either

it would definitely still be good to provide an ARM build through flatpak though, a fair amount of devices are ARM-based now

**Comment by JetpackDuba** [comment]
Thanks for the report!

Would you mind opening an issue here please https://github.com/flathub/com.jetpackduba.Gitnuro ?

**Comment by endim8** [comment]
Will do 👍
